/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoNotepad;

import java.util.ArrayList;

public class App {

    //定义一个arraylist叫Itemlist
    public void AddItem(String name,String time)
    {

    }


}
