/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoNotepad;

import java.io.*;
import java.util.ArrayList;

class Item{
    String itemname;
    String itemtime;
    String isFinished; //涉及到文件读写问题,故改为字符串，暂时不影响使用
    public Item(String name,String time)
    {
        this.itemname = name;
        this.itemtime = time;
        this.isFinished = "False";
    }
}

class App{
    ArrayList<Item> Itemlist = new ArrayList<Item>();


    public App()throws Exception{

        FileReader fr = new FileReader("NotePad.txt");
        char[] tempString = new char[100];
        int num,line=0,positon=0;
        while((num = fr.read(tempString))!=-1) {
            Item item = new Item("","");
            Itemlist.add(item);
            String temp="";
            for(int i=0;i<num;i++) {
                if(tempString[i] == ' ') {
                    if(positon == 0)
                    Itemlist.get(line).itemname = temp;
                    if(positon == 1)
                        Itemlist.get(line).itemtime = temp;
                    if(positon == 2)
                        Itemlist.get(line).isFinished = temp;
                    temp="";     //存放字符串
                    positon ++;  //是属性的位置，三个属性012
                }else {
                    temp+=tempString[i];
                }
            }
            positon = 0;
            line++;     //item的三项属性的组别
        }

    }

    public void WriteFile() throws Exception {
        File file=new File("NotePad.txt");
        BufferedWriter bw=new BufferedWriter(new FileWriter(file));
        for(int i=0;i<Itemlist.size();i++){
            bw.write(Itemlist.get(i).itemname+' ');
            bw.write(Itemlist.get(i).itemtime+' ');
            bw.write(Itemlist.get(i).isFinished+' ');
            bw.newLine();
        }
        bw.close();
    }
    public int  SearchTheItem(String name)
    {
        for(int i=0;i<Itemlist.size();i++){
            if(Itemlist.get(i).itemname == name)
                return i;
        }
        return -1;
    }
    public void AddTheItem(String name,String time) throws Exception  //增加条目
    {
        Item item = new Item(name,time);
        Itemlist.add(item);
        try {
            WriteFile();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void DeleteTheItem(String name)
    {

        WriteFile();
    }
//    public void FinishTheItem(name)
//    {
//        SearchTheItem(name);
//       // 根据下表修改isfinished变量。
//    }

}


