/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoNotepad;

import java.io.*;
import java.util.ArrayList;
import java.util.Scanner;

class Item{
    private String itemName;
    private String itemTime;
    private String isFinished; //涉及到文件读写问题,故改为字符串，暂时不影响使用

    public Item(String name, String time)
    {
        this.itemName = name;
        this.itemTime = time;
        this.isFinished = "False";
    }

    public String gettername(){ return itemName; }
    public String gettertime(){ return itemTime; }
    public String getterisfinished(){ return isFinished; }

    public void FinishTheItem(){ this.isFinished = "True";}

}


class App{
    ArrayList<Item> Itemlist = new ArrayList<Item>();


    public App()throws Exception{

        BufferedReader fr = new BufferedReader(new FileReader("NotePad.txt"));
        String tempString = "";
        //read txt
        while((tempString = fr.readLine()) != null) {

            String[] takon;
            takon = tempString.split(",");
            Item item = new Item(takon[0], takon[1]);  //默认未完成
            if(takon[2].equals("True")) item.FinishTheItem();  //默认是未完成，若读取的是完成，设为完成
            Itemlist.add(item);

        }

    }


    public void WriteFile() throws Exception {
        File file=new File("NotePad.txt");
        BufferedWriter bw=new BufferedWriter(new FileWriter(file));
        for (Item item : Itemlist) {
            bw.write(item.gettername() + ',');
            bw.write(item.gettertime() + ',');
            bw.write(item.getterisfinished() + ',');
            bw.newLine();
        }
        bw.close();
    }


    public int  SearchTheItem(String name)
    {
        for(int i=0;i<Itemlist.size();i++){
            if(Itemlist.get(i).gettername().equals(name))
                return i;


        }
        return -1;
    }

    public void AddTheItem(String name,String time)  //增加条目
    {
        //不允许同名事项
        if (SearchTheItem(name) == -1) {
            Item item = new Item(name,time);
            Itemlist.add(item);
        }

        try {
            WriteFile();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void DeleteTheItem(String name)
    {
        try {
            int index = SearchTheItem(name);
            Itemlist.remove(index);
            WriteFile();
        }
        catch (ArrayIndexOutOfBoundsException e){
            System.out.println("The item is not exist!");
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }



    public void FinishTheItem(String name){
         int index = SearchTheItem(name);
         if( index != -1){
             if(Itemlist.get(index).getterisfinished().equals("False"))
             {
                 Itemlist.get(index).FinishTheItem();
             }
             else
             {
                 System.out.println("The item has finished before!");
             }
         }
         else {
             System.out.println("The item is not existfin!");
         }

        try {
            WriteFile();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

}


